# Book settings
title: My sample book
author: The Jupyter Book Community
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url                       : https://github.com/AnouarGanfoud/Gentsch  # Online location of your book
  path_to_book              : public
  branch                    : master  # Which branch of the repository should be used when creating links (optional)	

launch_buttons:
  notebook_interface: "jupyterlab"
  thebe                  : true
  binderhub_url: "https://mybinder.org"